AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      PackageType: Image
      ImageUri: palominos_algorithm:latest
      Architectures:
        - x86_64
      CodeUri: ./
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /ping
            Method: GET
